---
- name: Setup Jenkins
  hosts: jenkins
  become: yes
  vars:
    jenkins_hostname: localhost
    jenkins_plugins:
      - golang
      - git
      - github
      - nexus-artifact-uploader
      - publish-over-ssh
    jenkins_plugins_install_dependencies: true
  pre_tasks:
    - apt:
        pkg:
        - git
        - build-essential
        - jq
        state: present
    - npm:
        name: abao
        global: yes
  roles:
    - role: geerlingguy.jenkins

- name: Setup Nexus
  hosts: nexus
  become: yes
  vars:
    java_packages:
      - adoptopenjdk-8-hotspot-jre
    nexus_admin_password: admin
  pre_tasks:
    - apt:
        name: gpg
        state: present
    - apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    - apt_repository:
        repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
        state: present
        update_cache: true
  roles:
    - role: geerlingguy.java
    - role: ansible-thoteam.nexus3-oss

- name: Setup Word-Cloud-Generator
  hosts: staging
  become: yes
  roles:
    - role: devoinc.systemd_service
      systemd_service:
        wordcloud:
          enabled: yes
          exec_start: "/opt/wordcloud/word-cloud-generator"
          wanted_by: "multi-user.target"
  tasks:
    - file:
        path: /opt/wordcloud/
        state: directory
        mode: '0755'
        owner: vagrant

    - apt:
        name: curl
        state: present
